# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6be4e1f62381f09ec67a4f294139763e2300ac07da29f79a9741a17aed290568958868d0c62ef85738496b189a417baf2e177d79260083fe6e9a934fad710d77

test:
  secret_key_base: 19b32dd9aed3f8e2e9e303a7c666203b1a4e2de15ad660819c352a52b846095ac3cfbdf2569898d0a085d385f765502365504cc631850a9f1a1c5f48cd108234

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
